### Rota para listar todos os alunos
GET http://localhost:3001/api/aluno/perfil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2FvLnNpbHZhMUBlbWFpbC5jb20iLCJpYXQiOjE3MzcwNjUzMTksImV4cCI6MTczNzE1MTcxOX0.wKnP72dxsgyQtTDNgL_qZKUvFlYyF0BVgrdgefFu8oA
### Cadastrar alunos
POST http://localhost:3001/api/aluno/cadastrar
Content-Type: application/json

{
  "nome": "João 1",
  "notas": 5,
  "email": "joao.silva1@email.com",
  "senha":"12345678"
}

### Atualizar alunos
PUT http://localhost:3001/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJqb2FvLnNpbHZhMUBlbWFpbC5jb20iLCJpYXQiOjE3MzcwNjUzMTksImV4cCI6MTczNzE1MTcxOX0.wKnP72dxsgyQtTDNgL_qZKUvFlYyF0BVgrdgefFu8oA

{
  "nome": "João Editado",
  "notas": 85.5,
  "email": "joao.silva1@email.com",
  "senha":"12345678"
}

### Deletar alunos
DELETE http://localhost:3001/api/aluno/perfil
Content-Type: application/json
Authorization: Bearer 


### Cadastrar alunos
DELETE http://localhost:3001/api/aluno/perfil
Content-Type: application/json

### Login aluno
POST http://localhost:3001/api/aluno/login
Content-Type: application/json

{
  "email": "joao.silva1@email.com",
  "senha":"12345678"
}